### ISSUE TITLE
create user accounts on Market with order history

### ISSUE THREAD

**Issue by davidmooreppf** [brickhousecoop/briet#20]
When a customer purchases books on Market, and after the purchases are approved by our admin in Stripe, 

Enable customer to login to Market with their email, click magic link, and see order history page. 

With some sort of download ability for books. 

**TODO**

- [ ] Expand `pages/order/[id].js` to support completed/approved orders, showing download
- [x] Add `pages/account/[customerId]/orders` to list orders
- [ ] Add `pages/account/[customerId]/library` to list books purchased, and quantity

**Comment by ronibhakta1** [comment]
@davidmooreppf @unitof  I have looked in the issue. Looks like there are lot of things going on and I need a better clear path which needs to be achived. To start the work I have to know how you imprort dummy data and test things. 

If someone can guide me it will be helpful.

**Comment by davidmooreppf** [comment]
Let's please get this set up and smoothed out first thing today, Jacob.

**Comment by ronibhakta1** [comment]
> Let's please get this set up and smoothed out first thing today, Jacob.

@unitof If you can breakdown the step's to set it up it will be easier to me.
